# Generated by Django 3.2.15 on 2022-09-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPannel', '0002_auto_20220905_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='is_group',
        ),
    ]
