# Generated by Django 3.2.15 on 2022-09-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPannel', '0003_remove_messages_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
