# Generated by Django 4.2.1 on 2023-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPannel', '0007_alter_messages_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
