# Generated by Django 3.2.15 on 2022-09-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_unfollow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_unfollowed',
            field=models.BooleanField(default=False),
        ),
    ]
